### ISSUE TITLE
Consider exporting the mySQL type

### ISSUE THREAD

**Issue by clns** [hgfischer/mysqlsuperdump#11]
Would you consider exporting the [`mySQL`](https://github.com/hgfischer/mysqlsuperdump/blob/8eb939c7d19b642610b269e32ee5c78b8e0486e5/dumper/mysql.go#L17) type? I understand the plans to refactor this into an interface to support multiple database engines, but for now I think it would be good to be able to see the [documentation](http://godoc.org/github.com/hgfischer/mysqlsuperdump/dumper), since you already wrote it. It's a shame not being able to see it :smile:

**Comment by hgfischer** [comment]
Please, explain your use-case.

**Comment by clns** [comment]
I did. Just to be able to see the API on [godoc.org](http://godoc.org/github.com/hgfischer/mysqlsuperdump/dumper)

**Comment by hgfischer** [comment]
You can still see it through the source-code. I just don't want to export this type. Sorry.

**Comment by clns** [comment]
Sure, np.
