### ISSUE TITLE
Filter doesn't work

### ISSUE THREAD

**Issue by alvaroemmanuel** [hgfischer/mysqlsuperdump#9]
Filter options doesn't work at all. It does not matter whether I select "ignore" or "nodata", the dump still contains all the CREATE and data for the filtered tables.

**Comment by hgfischer** [comment]
Are you using the latest version?

**Comment by alvaroemmanuel** [comment]
I followed the install instructions... So, whatever version `go get github.com/hgfischer/mysqlsuperdump` gets is the one I use.

**Comment by hgfischer** [comment]
@alvaroemmanuel Can you send me your config?

**Comment by hgfischer** [comment]
@alvaroemmanuel Before, run this to force a update.
```
go get -u -v github.com/hgfischer/mysqlsuperdump
```

**Comment by hgfischer** [comment]
I guess I can close this, right @alvaroemmanuel ?

**Comment by alvaroemmanuel** [comment]
hey @hgfischer, sorry for the late response... I've tried `go get -u -v github.com/hgfischer/mysqlsuperdump` but still not working.

In the config file I have this:

`[filter]`
`papelweb = ignore`
`TestPages = ignore`

I also had some tables with spaces in the names and thought that it was the cause of the error, but I've tried removing them and still can't get mysqlsuperdump to ignore the selected tables, which looks weird to me.

**Comment by hgfischer** [comment]
@alvaroemmanuel  Please, post your entire config file with sensitive information edited.

**Comment by hgfischer** [comment]
Closing, since I got no more feedback about it.
